### PR TITLE
Added a couple of additional CLI arguments for benchmarking purposes.

### PR DESCRIPTION
**Pull request by jasonmccampbell**
If you are interested, I added a couple of additional command line arguments to mirror the llama.cpp default binary. These help with automating benchmarking tests.

Specifically:
* Note that the prompt now must be preceded by -p or --prompt to allow the prompt to be read from a file (-f / --file)
* Added specification for the number of threads to use
* The seed and context size can be specified as well.

Draft for now. I'll check to see if there are any docs impact if these changes are of interest.

### CODE REVIEW

**Comment by MarcusDunn** [comment]
Totally of interest, no doc changes required - I basically just use simple as a smoke test to see if I broke something catastrophically.

**Comment by jasonmccampbell** [comment]
Thanks, @MarcusDunn . Let me know if there's anything you'd like changed. And thank you for this project, hopefully I'll have an opportunity to contribute more in the future.

**Comment by MarcusDunn** [comment]
I'll merge as is. Nitpick wise the non-prompt args (as those are mutually exclusive) should be defaulted via clap. This should result in easier to maintain help messages + less logic in main.

**Comment by jasonmccampbell** [comment]
No rush on my end. I agree that clap defaults would make the code cleaner. I left them off in this case to avoid overriding (or duplicating) the core llama.cpp defaults and keep the behavior consistent. For example, llama.cpp defaults the number of threads to the number of cores in the system if unspecified. If you prefer the defaults are specified in clap, I'll switch it over.

**Comment by MarcusDunn** [comment]
That's absolutely better, you're right.

**Review by MarcusDunn — APPROVED** [review]

**Pull request merged**
