### PR TITLE
Enable native and vulkan features

### PR DESCRIPTION
**Pull request by estokes**
I've had pretty good luck with vulkan on Intel arc integrated GPUs, it's faster and more power efficient than using avx2-vnni on the CPU. I'm not sure if it was an oversight that the feature wasn't enabled, or if it just had not been tested.

I've tested it on ubuntu 22.04 on an Intel GPU. I'll try it on windows as soon as I have time.

### CODE REVIEW

**Comment by MarcusDunn** [comment]
AFAIK it just hasn't been tested, let me know how windows goes, but it's certainly not a requirement for this to be merged.

**Comment by babichjacob** [comment]
The Vulkan feature doesn't compile for me on Windows until I manipulate things a little (and I'm too unfamiliar with C / C++ / build processes to know if it'd be only on my end).

<details>
<summary>Error log (for --release but would be just about the same for debug too)</summary>

```
The following warnings were emitted during compilation:

warning: llama-cpp-sys-2@0.1.59: cl : Command line warning D9002 : ignoring unknown option '-static'

error: failed to run custom build command for `llama-cpp-sys-2 v0.1.59 (C:\Users\Jacob\Repositories\llama-cpp-rs\llama-cpp-sys-2)`

Caused by:
  process didn't exit successfully: `C:\Users\Jacob\Repositories\llama-cpp-rs\target\release\build\llama-cpp-sys-2-6e8c1942500ecdb9\build-script-build` (exit code: 1)
  --- stdout
  cargo:rerun-if-changed=./llama.cpp
  Generating bindings..
  Compiling Vulkan GGML..
  TARGET = Some("x86_64-pc-windows-msvc")
  OPT_LEVEL = Some("3")
  HOST = Some("x86_64-pc-windows-msvc")
  cargo:rerun-if-env-changed=CXX_x86_64-pc-windows-msvc
  CXX_x86_64-pc-windows-msvc = None
  cargo:rerun-if-env-changed=CXX_x86_64_pc_windows_msvc
  CXX_x86_64_pc_windows_msvc = None
  cargo:rerun-if-env-changed=HOST_CXX
  HOST_CXX = None
  cargo:rerun-if-env-changed=CXX
  CXX = None
  cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
  CRATE_CC_NO_DEFAULTS = None
  CARGO_CFG_TARGET_FEATURE = Some("cmpxchg16b,fxsr,lahfsahf,sse,sse2,sse3")
  DEBUG = Some("false")
  cargo:rerun-if-env-changed=CXXFLAGS_x86_64-pc-windows-msvc
  CXXFLAGS_x86_64-pc-windows-msvc = None
  cargo:rerun-if-env-changed=CXXFLAGS_x86_64_pc_windows_msvc
  CXXFLAGS_x86_64_pc_windows_msvc = None
  cargo:rerun-if-env-changed=HOST_CXXFLAGS
  HOST_CXXFLAGS = None
  cargo:rerun-if-env-changed=CXXFLAGS
  CXXFLAGS = None
  cargo:rerun-if-env-changed=CC_ENABLE_DEBUG_OUTPUT
  cargo:warning=cl : Command line warning D9002 : ignoring unknown option '-static'
  ggml-vulkan.cpp
  ./llama.cpp\ggml-vulkan.cpp(2): fatal error C1083: Cannot open include file: 'vulkan/vulkan_core.h': No such file or directory

  --- stderr


  error occurred: Command "C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.40.33807\\bin\\HostX64\\x64\\cl.exe" "-nologo" "-MD" "-O2" "-Brepro" "-static" "-I" "./thirdparty/Vulkan-Headers/include/" "-I" "./llama.cpp" "-W4" "/W4" "/Wall" "/wd4820" "/wd4710" "/wd4711" "/wd4820" "/wd4514" "-DGGML_SCHED_MAX_COPIES=4" "-DNDEBUG" "-D_XOPEN_SOURCE=600" "-DGGML_USE_VULKAN" "-FoC:\\Users\\Jacob\\Repositories\\llama-cpp-rs\\target\\release\\build\\llama-cpp-sys-2-d62327f2c000586a\\out\\30b5508d68fcb5a8-ggml-vulkan.o" "-c" "./llama.cpp\\ggml-vulkan.cpp" with args cl.exe did not execute successfully (status code exit code: 2).


warning: build failed, waiting for other jobs to finish...
```
</details>

First, I had to open a Developer PowerShell for VS 2022 so my `INCLUDE` and `LIB` environment variables would be set. (I only mention this and the following steps because I don't have to do them to compile llama.cpp on its own with `cmake`, if that's helpful)

Then, I had to add the Vulkan SDK Include and Lib directories to my `INCLUDE` and `LIB` environment variables:
```
nu
$env.INCLUDE = ($env.INCLUDE + ";C:\\VulkanSDK\\1.3.283.0\\Include")
$env.LIB = ($env.LIB + ";C:\\VulkanSDK\\1.3.283.0\\Lib")
```

and it seems `vulkan.lib` is called `vulkan-1.lib` instead, so I had to edit the line that this PR changes in `build.rs` from `println!("cargo:rustc-link-lib=vulkan");` to
```println!("cargo:rustc-link-lib=vulkan-1");```


After doing that stuff, I can compile and run the `simple` example (by updating it to expose a `vulkan` feature) and it shows me it indeed finds my GPU as a Vulkan device. Hope this helps to know and isn't noise!

**Comment by estokes** [comment]
Thanks that's good information. When I test windows I'll try to clean it up so it builds nicely on both platforms.

**Comment by estokes** [comment]
Ok, I've added the requisite "horrible things" to build.rs to make this build on windows. I also changed the examples to offload layers to the GPU if either vulkan or cuda is enabled. I tested simple with Phi3 on an rtx 4090 and it worked just fine and did see significant speedup vs CPU, obviously not as fast as cuda, but the advantage is it will run on literally anything.

To build it with vulkan now all you should need to do is `winget install KhronosGroup.VulkanSDK` and `cargo build --release --package=simple --target=native,vulkan`

**Comment by babichjacob** [comment]
It works for me without any of the extra steps from before. Thanks for working on this!

**Review by MarcusDunn — APPROVED** [review]
this looks great!

**Pull request merged**
