### PR TITLE
Added passthrough metadata information to help downstream projects build native libraries using llama.cpp build artifacts

### PR DESCRIPTION
**Pull request by anagri**
Added passthrough metadata information to help downstream projects build native libraries using llama.cpp build artifacts

Added INCLUDE pointing to llama.cpp source folder for header lookup 
Added OUT_DIR pointing to build output directory for object file lookup

This allows downstream projects access to llama.cpp header files, and llama.cpp object files to link with their own C-source and compile.

### CODE REVIEW

**Comment by MarcusDunn** [comment]
This looks good - is there somewhere you could point me to where `INCLUDE` and `OUT_DIR` are used (other projects, etc)?

https://doc.rust-lang.org/cargo/reference/build-scripts.html does not seem to mention it explicitly.

**Comment by MarcusDunn** [comment]
(don't worry about checks - I broke those myself)

**Comment by MarcusDunn** [comment]
https://kornel.ski/rust-sys-crate mentions it and it seems its pretty ad-hoc. Thanks for the PR!

**Comment by anagri** [comment]
> This looks good - is there somewhere you could point me to where `cargo:INCLUDE` and `cargo:OUT_DIR` are used (other projects, etc)?
> 
> https://doc.rust-lang.org/cargo/reference/build-scripts.html does not seem to mention it explicitly.

I am new to rust as well. The above were suggested by ChatGPT when i was stuck extending llama.cpp with my own C-code. 

Glad you found the link - https://kornel.ski/rust-sys-crate where include is mentioned.

Thanks for the merge.

**Comment by MarcusDunn** [comment]
I may end up removing the OUT_DIR one, I imagine using the environment variable is preferred.

**Pull request merged**
